<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>97941c4b-2609-4c45-9b71-2f0295271366</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/cp_cambodia/images/menu/i_exit.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BODY_TR_HEADER&quot;)/td[@class=&quot;content&quot;]/table[@class=&quot;header&quot;]/tbody[1]/tr[1]/td[@class=&quot;right&quot;]/table[@class=&quot;FORM&quot;]/tbody[1]/tr[1]/td[1]/div[@class=&quot;BUTTON FLOAT_RIGHT BORDER_LEFT&quot;]/a[1]/img[1]</value>
   </webElementProperties>
</WebElementEntity>
